# Production profile hardening: no SQL logging and no automatic schema mutation.
spring.jpa.show-sql=false
# If commented -> It will wipe the database and create a new one on startup, which is not desired in production.
spring.jpa.hibernate.ddl-auto=validate
